### ISSUE TITLE
Issue running OpenHIM Core using Instant v2

### ISSUE THREAD

**Issue by brianraila** [openhie/instant-v2#64]
Attempting to run OpenHIM using Instant v2, with the sample profile below:

```
- name: hie
    packages:
      - interoperability-layer-openhim
      - reverse-proxy-nginx
      - client-registry-santempi
      - fhir-datastore-hapi-fhir

    envFiles:
      - .env.dev
    dev: true
    only: true

```

Upon starting OpenHIM, I get the error below from the OpenHIM Core container, hence unable to use it.

```
MongooseError: Operation `agendaJobs.createIndex()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:175:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

2023-11-17T09:29:36.155Z [worker4] error: MongooseError: Operation `keystores.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:175:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

Additional Logs:

```
Executing: bash interoperability-layer-openhim//swarm.sh up dev
 ❕ [Interoperability Layer Openhim] Running package in Single node mode

 ❕ [Interoperability Layer Openhim] Running package in DEV mode

 ❕ [Interoperability Layer Openhim] Waiting for openhim_mongo-1 to be Running... Done

 ❕ [Interoperability Layer Openhim] Waiting for openhim_openhim-core to be Running... Done

 ❕ [Interoperability Layer Openhim] Waiting for openhim_openhim-console to be Running... Done

 ❕ [Interoperability Layer Openhim] Waiting OpenHIM Core to be running and responding

 🔶 [Interoperability Layer Openhim] Warning: Waited 60 seconds for openhim-core status check. This is taking longer than it should...
```

Kindly help out.
